// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn4CLJYjP7u6EydiDwVTBJgyWeuhnmpVQ',
    appId: '1:906959724835:web:306b90096361835029ac96',
    messagingSenderId: '906959724835',
    projectId: 'pfirebase-d9ea4',
    authDomain: 'pfirebase-d9ea4.firebaseapp.com',
    storageBucket: 'pfirebase-d9ea4.firebasestorage.app',
    measurementId: 'G-ZM7821K3P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBONi7QOCvwoHdiCeHnZTgYTK9KhII1mvA',
    appId: '1:906959724835:android:25cd0030c69b449e29ac96',
    messagingSenderId: '906959724835',
    projectId: 'pfirebase-d9ea4',
    storageBucket: 'pfirebase-d9ea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKeE4yDL6QwpqvxmRBrUQqsIf0QxwjMic',
    appId: '1:906959724835:ios:602824d91ceb216d29ac96',
    messagingSenderId: '906959724835',
    projectId: 'pfirebase-d9ea4',
    storageBucket: 'pfirebase-d9ea4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCihuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKeE4yDL6QwpqvxmRBrUQqsIf0QxwjMic',
    appId: '1:906959724835:ios:602824d91ceb216d29ac96',
    messagingSenderId: '906959724835',
    projectId: 'pfirebase-d9ea4',
    storageBucket: 'pfirebase-d9ea4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCihuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn4CLJYjP7u6EydiDwVTBJgyWeuhnmpVQ',
    appId: '1:906959724835:web:8e192a2c1ec8145d29ac96',
    messagingSenderId: '906959724835',
    projectId: 'pfirebase-d9ea4',
    authDomain: 'pfirebase-d9ea4.firebaseapp.com',
    storageBucket: 'pfirebase-d9ea4.firebasestorage.app',
    measurementId: 'G-J4E89RR4B2',
  );
}
